query ($cursor: String!) {
  viewer {
    sponsorshipsAsMaintainer(includePrivate: true, first: 50, after: $cursor) {
      edges {
        node {
          sponsorEntity {
            __typename
            ... on User {
              login
              email
              name
              databaseId
            }
            ... on Organization {
              login
              email
              name
              databaseId
            }
          }
          tier {
            id
            name
            isOneTime
            isCustomAmount
            monthlyPriceInDollars
            monthlyPriceInCents
            closestLesserValueTier {
              id
              name
            }
          }
          id
          isOneTimePayment
          tierSelectedAt
        }
      }
      pageInfo {
        endCursor
        startCursor
        hasNextPage
      }
    }
  }
}
